name : Hello
on : 
  push :
    branches : main
jobs : 
  build : 
    runs-on : ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - name : java workflow
        run : echo hello from zversal 